FROM python:3.7

WORKDIR /app

COPY ./twitter_bot /app/twitter_bot
COPY ./config.json /app
COPY ./requirements.txt /app
COPY ./models /app/models

RUN pip install -r /app/requirements.txt
RUN pip install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_armv7l.whl

ENTRYPOINT ["python", "/app/twitter_bot/main.py"]

