FROM fkropfhamer/python-tensorflow-lite-numpy-raspberrypi

WORKDIR /app

COPY ./twitter_bot /app/twitter_bot
COPY ./config.json /app
COPY ./models /app/models

RUN pip install tweepy pillow

ENTRYPOINT ["python", "/app/twitter_bot/main.py"]

